import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Enatega-Food Delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add the favicon */}
        <link rel="icon" href="/logo.svg" type="image/png" />
      </head>
      <body className="text-xl font-sans">{children}</body>
    </html>
  );
}
